# Generated by Django 4.2.6 on 2023-10-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRegular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('fechaLogin', models.DateTimeField(auto_now_add=True)),
                ('duracionLogin', models.IntegerField(default=0)),
                ('clicksBoton1', models.IntegerField(default=0)),
                ('clicksBoton2', models.IntegerField(default=0)),
            ],
        ),
    ]
